### ISSUE TITLE
MongoDBStore session broke, needs a clear fix

### ISSUE THREAD

**Issue by Markalot787** [Colt/YelpCamp#14]
const MongoDBStore = require("connect-mongo")(session);

const secret = process.env.SECRET || 'thisshouldbeabettersecret!';

const store = new MongoDBStore({
    url: dbUrl,
    secret,
    touchAfter: 24 * 60 * 60
});

store.on("error", function (e) {
    console.log("SESSION STORE ERROR", e)
})

const sessionConfig = {
    store,
    name: 'session',
    secret,
    resave: false,
    saveUninitialized: true,
    cookie: {
        httpOnly: true,
        // secure: true,
        expires: Date.now() + 1000 * 60 * 60 * 24 * 7,
        maxAge: 1000 * 60 * 60 * 24 * 7
    }
}

app.use(session(sessionConfig));

**Comment by Markalot787** [comment]
//replaced with this solution i found but still broke

const mongoStore = require("connect-mongo");
const secret = process.env.SECRET || 'thisshouldbeabettersecret';

const sessionConfig = {
  name: 'session',
  secret,
  resave: false,
  saveUninitialized: true,
  store: mongoStore.create({
      mongoUrl: dbUrl,
      secret: secret,
      touchAfter: 24 * 60 * 60,
  }),
  cookie: {
      httpOnly: true,
      expires: Date.now()+ 1000 * 60 * 60 * 24 * 7,
      maxAge: 1000 * 60 * 60 * 24 * 7
  }
}

sessionConfig.store.on("error", function (e) {
  console.log("SESSION STORE ERROR", e)
});

app.use(session(sessionConfig))

**Comment by nax3t** [comment]
What's the error that you're getting?

**Comment by Markalot787** [comment]
i ended up with this 

const secret = process.env.SECRET || 'thisshouldbeabettersecret';


const store = mongoStore.create({
    mongoUrl: dbUrl,
    secret,
    touchAfter: 24 * 60 * 60

});

// store.on("error", function (e) {
//     console.log("SESSION STORE ERROR", e)
// })

const sessionConfig = {
  store,
  name: 'session',
  secret,
  resave: false,
  saveUninitialized: true,
  cookie: {
      httpOnly: true,
      // secure: true,
      expires: Date.now() + 1000 * 60 * 60 * 24 * 7,
      maxAge: 1000 * 60 * 60 * 24 * 7
  }
}

// sessionConfig.store.on("error", function (e) {
//   console.log("SESSION STORE ERROR", e)
// });

app.use(session(sessionConfig))

**Comment by Markalot787** [comment]
const store = mongoStore.create({
                         ^

TypeError: mongoStore.create is not a function
    at Object.<anonymous> (D:\apps\YelpCamp-master2\app.js:54:26)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)      
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yelpcamp@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yelpcamp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Abdulrasheedar** [comment]
DId you find the solution for this ?? @Markalot787

**Comment by prince1911** [comment]
Assertion failed: You must provide either mongoUrl|clientPromise|client in options
C:\Users\Prince\YelpCamp\node_modules\connect-mongo\build\main\lib\MongoStore.js:119
            throw new Error('Cannot init client. Please provide correct options');
            ^

Error: Cannot init client. Please provide correct options
    at new MongoStore (C:\Users\Prince\YelpCamp\node_modules\connect-mongo\build\main\lib\MongoStore.js:119:19)
    at Object.<anonymous> (C:\Users\Prince\YelpCamp\app.js:51:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by U-4D89** [comment]
Same issue here, I installed the same version that Colt uses in the videos.
`npm i connect-mongo@^3.2.0`

**Comment by nax3t** [comment]
please see [here](https://www.udemy.com/course/the-web-developer-bootcamp/learn/lecture/22346322#questions/14175216)

**Comment by Shksantosh** [comment]
- > _**`**_`MongoDB running problem not connecting to Database here that  solution for ...... in mongoAtlas settings`_**`**_





1

Go to IP Access List view.icons/link.png

In the Security section of the left navigation, click Network Access. The IP Access List tab displays.

Click Add IP Address.

2

Enter an IP address, CIDR block, or Security Group ID.icons/link.png

IMPORTANT

Ensure that you add the IP address you will use to access MongoDB as the admin user.

Enter the desired IP address or CIDR-notated range of addresses:

Entry

Grants

An IP address

Access from that address.

A CIDR-notated range of IP addresses

Access from the designated range of addresses.

For peer VPC connections, you can specify the CIDR block (or a subset) or the associated Security Group.

The Internet provides online tools for converting a range of IP addresses to CIDR, such as http://www.ipaddressguide.com/cidr.

IMPORTANT

Adding the CIDR 0.0.0.0/0 allows access from anywhere. Ensure that strong credentials (username and password) are used for all database users when allowing access from anywhere.

Security Group ID (AWS Only)

Access via Security Group membership from a peered VPC.

IMPORTANT

Atlas does not support adding AWS security groups to IP access lists in projects with VPC peering connections in multiple regions.

3

(Optional) Set the IP access list as temporary.icons/link.png

Check the Save as temporary access list option to specify a length of time that the IP address will be added. After this time, Atlas removes the address from the IP access list. You can select one of the following time periods for the address to be added:

6 hours

1 day

1 week

In the IP Access List view, temporary access list entries display the time remaining until the address will expire. Once the IP address expires and is deleted, any client or application attempting to connect to the cluster from the address can't access the cluster.

**Comment by benilrichards** [comment]
```
const MongoDBStore = require("connect-mongo")  // change this line

const store = MongoDBStore.create({  // change this line
	mongoUrl: dbUrl,  // change this line
	secret,
	touchAfter: 24 * 60 * 60,
});
```
This worked for me.

**My installed dependency version**
"connect-mongo": "^4.6.0"

**Comment by naeemishere** [comment]
@benilrichards  Thanks for sharing this solution, I had similar issue in console "Error: Cannot init client. Please provide correct options", I'm using ("^4.6.0"). Although variable name i used is "MongoStore" instead of "MongoDBStore" and it still worked! 


```
const store = new MongoStore({
    mongoUrl: dbUrl,
    secret: 'thisshouldbeabettersecret!',
    touchAfter: 24 * 60 * 60
}); 
```

**Comment by I-karmayogi** [comment]
still showing me the error with your above code 
Any idea with new versions?
